services:
  postgres:
    container_name: cakedesigner_api_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=msilva
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cakedesigner_api

    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: cakedesigner_api
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cakedesigner_api
      SPRING_DATASOURCE_USERNAME: msilva
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Ajuste a porta conforme seu app
      SERVER_PORT: 8080
    depends_on:
      - postgres

volumes:
  pgdata:
