services:
  postgres:
    container_name: cakedesigner_api_postgres
    image: postgres
    ports: 
    - 5432:5432
    environment:
      - POSTGRES_USER=msilva
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cakedesigner_api